### PR TITLE
Add a hint that this bundle is not used by webfactory any more

### PR DESCRIPTION
**Pull request by sebastiankugler**
I recently realized that this bundle is (technically) not used any more in new projects we start here at webfactory. I think it would be fair to indicate this in the readme.

### CODE REVIEW

**Comment by sebastiankugler** [comment]
@polarbirke @MalteWunsch @relthyg since we recently discussed this topic: What do you think of adding a hint to the readme?

**Comment by polarbirke** [comment]
I think that's fair. I edited the hint slightly.

**Comment by relthyg** [comment]
How about another hint that this bundle is obsolete and will not be updated in the future?

**Comment by sebastiankugler** [comment]
> How about another hint that this bundle is obsolete and will not be updated in the future?

I wouldn't go that far but also wouldn't object. I think that should be another PR.

**Review by MalteWunsch — APPROVED** [review]

**Pull request merged**
